# Generated by Django 4.2.16 on 2024-11-17 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ruleversion",
            options={"ordering": ["-version"]},
        ),
        migrations.AlterModelOptions(
            name="storedrule",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AlterUniqueTogether(
            name="storedrule",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="severity",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="type",
            field=models.CharField(choices=[("sigma", "Sigma"), ("yara", "YARA"), ("snort", "Snort")], max_length=10),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterModelTable(
            name="ruleversion",
            table="api_rule_version",
        ),
        migrations.AlterModelTable(
            name="storedrule",
            table="api_stored_rule",
        ),
    ]
