# Generated by Django 4.2.16 on 2024-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_ruleversion_options_alter_storedrule_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storedrule",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="storedrule",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="integration",
            field=models.CharField(default="manual", max_length=50),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="severity",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="storedrule",
            name="type",
            field=models.CharField(max_length=50),
        ),
    ]
