# Generated by Django 4.2.16 on 2024-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_storedrule_options_storedrule_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedrule",
            name="source",
            field=models.CharField(default="Custom", max_length=50),
        ),
    ]
