# Generated by Django 4.2.16 on 2024-12-02 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("integration", models.CharField(default="manual", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DetectIQ", "DetectIQ"),
                            ("SigmaHQ", "SigmaHQ"),
                            ("YARA-Forge", "YARA-Forge"),
                            ("Snort3 Community", "Snort3 Community"),
                        ],
                        default="DetectIQ",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                ("version", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="rules.storedrule"
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("rule", "version")},
            },
        ),
    ]
