# Generated by Django 4.2.16 on 2024-12-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedrule",
            name="package_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
